### PR TITLE
S3 Store

### PR DESCRIPTION
**Pull request by YukSeungChan**
Hello,

I have created the S3Store feature. There are a lot of Insufficient implementation...
Let me know enhancement point.

### CODE REVIEW

**Comment by YukSeungChan** [comment]
Ohh... S3Store tests have to require options (bucket, access_key...).
TravisCi didn't have keys. How can I test normally on TravisCI?

**Comment by pylover** [comment]
Thanks. But the tests are failing

**Comment by pylover** [comment]
You have to create a s3 mockup server. And run tests with that. That's why this task is not completed yet

**Comment by YukSeungChan** [comment]
umm.. mockup server means like this ?

https://github.com/tornadoweb/tornado/blob/master/demos/s3server/s3server.py

**Comment by pylover** [comment]
Interesting. Yes, that's it

**Comment by YukSeungChan** [comment]
Testing using the mockup server is great, but isn't it more accurate to test on the real server?
As i know, S3Store tests of sqlalchemy-imageattach are run with real S3 server.

**Comment by pylover** [comment]
yes, but we have to tune the mockup server to act accurately.

**Comment by YukSeungChan** [comment]
change tests to using mockup server. but decreased coverage.. I'll check it.

**Comment by pylover** [comment]
Thanks a lot. it's ok to make the mockup server on `setUp` methdo and cleanup it on `tearDown`

**Comment by YukSeungChan** [comment]
TODO
------
1. prefix test
2. S3Error test

**Comment by YukSeungChan** [comment]
@pylover S3 mockup server doesn't occur any errors. how can i test S3Error..?

**Comment by pylover** [comment]
We have change the mockup server to act like s3 errors

**Comment by YukSeungChan** [comment]
@pylover added error tests.

**Comment by pylover** [comment]
Wow, great thanks Mr @YukSeungChan

**Pull request merged**
